#!/usr/bin/env python3
"""Render the targeted amendment proposal for REL-ART-005.KA.RIFTSTALKER.

Author: Angelis Pseftis.

The owner selected the existing 22-bone quadruped rig as the production direction on 2026-09-07 and
directed that a targeted amendment be prepared, including the bone hierarchy and each bone's purpose.
This generates that document FROM the generator's own bone table, so the proposal cannot drift from the
asset it describes. `--check` re-renders and compares.

  python3 make_card_amendment.py [--check]
"""
from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "tools"))
sys.path.insert(0, HERE)
import build_riftstalker as rs  # noqa: E402

TARGET = os.path.join(HERE, "card-amendment-REL-ART-005.KA.RIFTSTALKER.md")


def render() -> str:
    skeleton = rs.build_skeleton()
    lines = [
        "---",
        "title: Targeted amendment proposal — REL-ART-005.KA.RIFTSTALKER .ANIM_RIG",
        "author: Angelis Pseftis",
        "creator: Angelis Pseftis",
        "created: 2026-09-07",
        "status: PROPOSAL. The requirements document has NOT been amended and this asset is NOT technically accepted.",
        "generated_from: build_riftstalker.py BONES (do not edit this file by hand)",
        "---",
        "",
        "# Targeted amendment proposal — `REL-ART-005.KA.RIFTSTALKER` `.ANIM_RIG`",
        "",
        "## What this is",
        "",
        "The owner selected the existing 22-bone quadruped rig as the production direction on 2026-09-07,",
        "and directed that a limb segment and the caster's independent aim must NOT be removed merely to",
        "reach 14 bones. This proposes the smallest change to the card that records that selection.",
        "",
        "**It is a proposal.** `Docs/Requirements.md` is unchanged, amending it is outside this worktree's",
        "authority, and nothing here constitutes technical acceptance.",
        "",
        "## The discrepancy, stated plainly",
        "",
        "| | Value |",
        "|---|---|",
        "| Card `.ANIM_RIG` as written | 14-bone kinematic rigging layout |",
        f"| Asset as built | {len(skeleton.bones)}-bone layout |",
        f"| Difference | {len(skeleton.bones) - 14} bones |",
        "",
        "The card's figure and the concept's anatomy are inconsistent. **I do not know why the card says 14.**",
        "An earlier note of mine suggested the figure implied the card intended a biped; that was an",
        "inference about provenance I cannot support, and it is withdrawn. The only established facts are",
        "the number in the card, the four-legged animal in the selected concept, and the owner's selection",
        "of the quadruped.",
        "",
        "Until an authoritative amendment is applied, the asset is **non-compliant with the card's",
        "`.ANIM_RIG` clause as written**, and that is recorded in its manifest and README rather than",
        "treated as settled.",
        "",
        "## Proposed replacement text for `.ANIM_RIG`",
        "",
        "> `.ANIM_RIG`: 22-bone kinematic rigging layout for a quadruped chassis: a root, a body, a",
        "> two-bone forward prow, a two-bone caster mount that aims independently of the gait, and four",
        "> limb chains of four bones each. Skeleton layout carries fixed named sockets:",
        "> `VFX_Muzzle_Shard_01`, `VFX_Molt_Origin_Base`, and `Target_Hitbox_Center`. Locomotion requires",
        "> direction-independent movement speeds and turn rates with instant snaps under Reduced Motion.",
        "",
        "Only the bone count and the chassis description change. The socket names, the locomotion clause",
        "and every other clause of the card are untouched.",
        "",
        "## Bone hierarchy and purpose",
        "",
        "| # | Bone | Parent | Head (cm) | Purpose |",
        "|---|---|---|---|---|",
    ]
    for index, bone in enumerate(skeleton.bones, start=1):
        head = ", ".join(f"{v:g}" for v in bone.head)
        parent = bone.parent if bone.parent else "—"
        lines.append(f"| {index} | `{bone.name}` | `{parent}` | ({head}) | {bone.purpose} |")
    limb = sum(1 for b in skeleton.bones if b.name.split("_")[0] in rs.LEG_TAGS)
    lines += [
        "",
        "## Why the count cannot fall to 14 without losing something the owner kept",
        "",
        f"- The four limb chains account for **{limb} bones** on their own, before any body, prow or caster.",
        "- Dropping one segment per limb reaches 18, still above 14, and costs the knee articulation the",
        "  gait depends on.",
        "- Dropping the two-bone caster mount reaches 20 and costs the independent aim that canon's",
        "  \"fires while it moves\" requires.",
        "- Reaching 14 needs both, which the owner's ruling of 2026-09-07 excludes.",
        "",
        "## What this proposal does not do",
        "",
        "- It does not amend `Docs/Requirements.md`.",
        "- It does not waive the card's three vertex ID channels for public molting phase transitions,",
        "  which remain required and unimplemented.",
        "- It does not assert technical acceptance of the asset.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        ok = current == text
        print(f'{{"check": "{"ok" if ok else "drift"}", "target": "{os.path.basename(TARGET)}"}}')
        return 0 if ok else 1
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f'{{"written": "{os.path.basename(TARGET)}", "bones": {len(rs.build_skeleton().bones)}}}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
