#!/usr/bin/env python3
"""Render the Kharuun provisional asset cards from their JSON source.

Author: Angelis Pseftis.

`kharuun-asset-cards.json` is the single source; this writes `kharuun-asset-cards.md` from it so the
readable document and the machine-readable contract cannot drift. `--check` re-renders into memory and
compares, the same way every generator here checks its own outputs.

  python3 render_kharuun_cards.py [--check]
"""
from __future__ import annotations

import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "kharuun-asset-cards.json")
TARGET = os.path.join(ROOT, "kharuun-asset-cards.md")


def _bullets(items) -> list:
    return [f"* {line}" for line in items]


def render(data: dict) -> str:
    a = data["authority"]
    out = [
        "---",
        f"title: {data['title']}",
        f"author: {data['author']}",
        f"creator: {data['creator']}",
        f"created: {data['created']}",
        "status: PROVISIONAL production contracts; not an amendment to Docs/Requirements.md and not owner acceptance",
        "generated_from: kharuun-asset-cards.json (do not edit this file by hand)",
        "---",
        "",
        f"# {data['title']}",
        "",
        "**This document is generated.** Edit [kharuun-asset-cards.json](kharuun-asset-cards.json) and re-run",
        "`python3 tools/render_kharuun_cards.py`.",
        "",
        "## Authority and boundary",
        "",
        f"**Status.** {a['status']}",
        "",
        f"**Source.** {a['source']}",
        "",
        "**What this is not.**",
        "",
    ]
    out += _bullets(a["what_this_is_not"])
    out += ["", "**Requirements that bind above these cards.**", ""]
    out += _bullets(a["binding_requirements_above_these_cards"])
    out += ["", "## Faction rules", "", "| Rule | Value |", "|---|---|"]
    for key, value in a["faction_rules"].items():
        out.append(f"| `{key}` | {value} |")
    out += ["", "## Cards", ""]
    out.append("| Card | Subject | LOD0 | LOD1 | Status |")
    out.append("|---|---|---|---|---|")
    for c in data["cards"]:
        p = c["mesh_prop"]
        out.append(f"| `{c['card_id']}` | {c['subject']} | {p['lod0_triangles']:,} | {p['lod1_triangles']:,} | {c['status']} |")
    out.append("")
    for c in data["cards"]:
        p = c["mesh_prop"]
        out += [f"### {c['card_id']} — {c['subject']}", ""]
        out += [
            "| Field | Value |", "|---|---|",
            f"| Status | {c['status']} |",
            f"| Package | `{c['package_id']}` |",
            f"| Production asset | `{c['production_asset_id']}` |",
            f"| Canon | {c['canon']} |",
            f"| Function | {c['function']} |",
            "",
            "**.MESH_PROP.** "
            f"LOD0 ceiling {p['lod0_triangles']:,} triangles; LOD1 ceiling {p['lod1_triangles']:,}. "
            f"Scope: {p['scope']}. "
            + (f"Footprint {p['footprint_tiles'][0]}x{p['footprint_tiles'][1]} tiles. " if p.get("footprint_tiles") else "")
            + f"Nanite {'on' if p['nanite'] else 'off'}. Pivot at the {p['pivot']}."
            + (f" {p['budget_note']}" if p.get("budget_note") else ""),
            "",
            f"**.TEX_MAPS.** {c['tex_maps']}",
            "",
            f"**.MAT_RULE.** Construction: {c['mat_rule']['construction']} Emissive: {c['mat_rule']['emissive']} "
            f"Forbidden: {c['mat_rule']['forbidden']}",
            "",
            "**.COMPONENTS.**", "",
        ]
        out += _bullets(c["components"])
        m = c["motion"]
        out += ["", f"**.ANIM_RIG.** {m['rig']}"]
        if m.get("articulated_requirement"):
            out += ["", f"**.ARTICULATION.** {m['articulated_requirement']}"]
        if m.get("anatomy_correction"):
            a = m["anatomy_correction"]
            out += ["", f"**.ANATOMY_CORRECTION ({a['date']}).** {a['superseded']} {a['status']}",
                    "", "Source references:", ""]
            out += _bullets(a["source_references"])
            out += ["", f"Owner: {a['confirmed_by_owner']}"]
        if m.get("acceptance"):
            out += ["", f"**.ACCEPTANCE.** {m['acceptance']}"]
        if m.get("clips"):
            out += ["", "**.CLIPS.** " + ", ".join(f"`{x}`" for x in m["clips"]) + "."]
        out += ["", f"**.ROOT_MOTION.** {m['root_motion']}", "",
                "**.SOCKETS.** " + ", ".join(f"`{s}`" for s in c["sockets"]) + ".", "",
                "**.STATES.**", "", "| State | Read |", "|---|---|"]
        for name, read in c["states"].items():
            out.append(f"| `{name}` | {read} |")
        out += ["", "**.READABILITY.**", ""]
        out += _bullets(c["readability"])
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with open(SOURCE, encoding="utf-8") as handle:
        data = json.load(handle)
    text = render(data)
    if args.check:
        current = open(TARGET, encoding="utf-8").read() if os.path.exists(TARGET) else ""
        ok = current == text
        print(json.dumps({"check": "ok" if ok else "drift", "target": os.path.basename(TARGET),
                          "cards": len(data["cards"])}))
        return 0 if ok else 1
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(json.dumps({"written": os.path.basename(TARGET), "cards": len(data["cards"]),
                      "bytes": len(text)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
