// EchoesGlassScarDressingPack.h
// GENERATED FILE - do not edit by hand.
// Generated by Content/World/Tools/emit_dressing_pack_header.py from the
// frozen dressing pack Content/World/Generated/Dressing/glass_scar_dressing_pack_v1.json
// authored against Content/World/Generated/GlassScar/glass_scar_compiled_map_pack_v1.json.
// Verify:   python3 Content/World/Tools/emit_dressing_pack_header.py --check
// Rewrite:  python3 Content/World/Tools/emit_dressing_pack_header.py --write
// Every record below was re-verified at emission to stand on a cell the
// compiled map pack marks blocked. The runtime re-checks against live terrain
// and hides any record whose tile is unexplored or reshaped open. Presentation
// only: nothing here enters simulation, fog authority, saves, or checksums.

#pragma once

#include <cstdint>

namespace echoes::world::glass_scar_dressing
{

inline constexpr std::int32_t kGridWidthTiles = 64;
inline constexpr std::int32_t kGridHeightTiles = 64;
inline constexpr char kPackFormat[] = "echoes-map-dressing-pack";
inline constexpr char kSiteId[] = "glass-scar";
inline constexpr std::int32_t kPackVersion = 1;
inline constexpr std::int32_t kSchemaVersion = 1;
inline constexpr char kPackSha256[] = "4db72ddc5eccc987d76022af7e1a2a4c4116b24b8f19407ce4c8024e9af61761";
// The compiled map pack these records were authored and verified against.
// The terrain view static_asserts this equals the compiled pack it binds.
inline constexpr char kBaseCompiledPackSha256[] = "6dbbe2f1a5bd7faec122e6050e5c2d27d4d56e3e94da357b239673ec4b6ab621";

enum class EDressingClass : std::uint8_t
{
    VitrifiedShelf = 0,
    GlassShard = 1,
};

struct FDressingClass
{
    EDressingClass Class;
    const char* Id;
    const char* MeshReference;
    const char* ReadsAs;
};

inline constexpr FDressingClass kClasses[2] = {
    {EDressingClass::VitrifiedShelf, "vitrified_shelf", "/Game/Art/Generated/World/Environment/SM_World_GlassScarShelf", "impassable vitrified shelf"},
    {EDressingClass::GlassShard, "glass_shard", "/Game/Art/Generated/World/Environment/SM_World_GlassScarShard", "impassable black-glass shard"},
};

struct FDressingRecord
{
    EDressingClass Class;
    std::uint8_t X;
    std::uint8_t Y;
    std::uint8_t OrientationOrdinal;
    std::uint8_t ScaleBand;
    std::int32_t CellIndex;
    const char* Id;
};

inline constexpr std::int32_t kRecordCount = 29;
inline constexpr FDressingRecord kRecords[kRecordCount] = {
    {EDressingClass::GlassShard, 8, 31, 3, 2, 1992, "drs_gs_shard_01"},
    {EDressingClass::GlassShard, 22, 31, 1, 2, 2006, "drs_gs_shard_02"},
    {EDressingClass::GlassShard, 36, 31, 3, 2, 2020, "drs_gs_shard_03"},
    {EDressingClass::GlassShard, 43, 31, 0, 2, 2027, "drs_gs_shard_04"},
    {EDressingClass::GlassShard, 8, 32, 0, 0, 2056, "drs_gs_shard_05"},
    {EDressingClass::GlassShard, 22, 32, 2, 0, 2070, "drs_gs_shard_06"},
    {EDressingClass::GlassShard, 36, 32, 0, 0, 2084, "drs_gs_shard_07"},
    {EDressingClass::GlassShard, 43, 32, 1, 0, 2091, "drs_gs_shard_08"},
    {EDressingClass::GlassShard, 8, 33, 1, 1, 2120, "drs_gs_shard_09"},
    {EDressingClass::GlassShard, 22, 33, 3, 1, 2134, "drs_gs_shard_10"},
    {EDressingClass::GlassShard, 36, 33, 1, 1, 2148, "drs_gs_shard_11"},
    {EDressingClass::GlassShard, 43, 33, 2, 1, 2155, "drs_gs_shard_12"},
    {EDressingClass::VitrifiedShelf, 8, 30, 2, 1, 1928, "drs_gs_shelf_01"},
    {EDressingClass::VitrifiedShelf, 16, 30, 2, 2, 1936, "drs_gs_shelf_02"},
    {EDressingClass::VitrifiedShelf, 20, 30, 2, 2, 1940, "drs_gs_shelf_03"},
    {EDressingClass::VitrifiedShelf, 24, 30, 2, 0, 1944, "drs_gs_shelf_04"},
    {EDressingClass::VitrifiedShelf, 28, 30, 2, 0, 1948, "drs_gs_shelf_05"},
    {EDressingClass::VitrifiedShelf, 36, 30, 2, 1, 1956, "drs_gs_shelf_06"},
    {EDressingClass::VitrifiedShelf, 40, 30, 2, 2, 1960, "drs_gs_shelf_07"},
    {EDressingClass::VitrifiedShelf, 44, 30, 2, 2, 1964, "drs_gs_shelf_08"},
    {EDressingClass::VitrifiedShelf, 52, 30, 2, 0, 1972, "drs_gs_shelf_09"},
    {EDressingClass::VitrifiedShelf, 10, 34, 0, 1, 2186, "drs_gs_shelf_10"},
    {EDressingClass::VitrifiedShelf, 18, 34, 0, 2, 2194, "drs_gs_shelf_11"},
    {EDressingClass::VitrifiedShelf, 22, 34, 0, 2, 2198, "drs_gs_shelf_12"},
    {EDressingClass::VitrifiedShelf, 26, 34, 0, 0, 2202, "drs_gs_shelf_13"},
    {EDressingClass::VitrifiedShelf, 38, 34, 0, 1, 2214, "drs_gs_shelf_14"},
    {EDressingClass::VitrifiedShelf, 42, 34, 0, 2, 2218, "drs_gs_shelf_15"},
    {EDressingClass::VitrifiedShelf, 46, 34, 0, 2, 2222, "drs_gs_shelf_16"},
    {EDressingClass::VitrifiedShelf, 54, 34, 0, 0, 2230, "drs_gs_shelf_17"},
};

}  // namespace echoes::world::glass_scar_dressing
