// EchoesLumeReachDressingPack.h
// GENERATED FILE - do not edit by hand.
// Generated by Content/World/Tools/emit_dressing_pack_header.py from the
// frozen dressing pack Content/World/Generated/Dressing/lume_reach_dressing_pack_v1.json
// authored against Content/World/Generated/Overlays/overlay_map_packs_v1.json.
// Verify:   python3 Content/World/Tools/emit_dressing_pack_header.py --check
// Rewrite:  python3 Content/World/Tools/emit_dressing_pack_header.py --write
// Every record below was re-verified at emission to stand on a cell the
// compiled map pack marks blocked. The runtime re-checks against live terrain
// and hides any record whose tile is unexplored or reshaped open. Presentation
// only: nothing here enters simulation, fog authority, saves, or checksums.

#pragma once

#include <cstdint>

namespace echoes::world::lume_reach_dressing
{

inline constexpr std::int32_t kGridWidthTiles = 64;
inline constexpr std::int32_t kGridHeightTiles = 64;
inline constexpr char kPackFormat[] = "echoes-map-dressing-pack";
inline constexpr char kSiteId[] = "lume-reach";
inline constexpr std::int32_t kPackVersion = 1;
inline constexpr std::int32_t kSchemaVersion = 1;
inline constexpr char kPackSha256[] = "6fc3f8f7d2362097462a1f8508081892d5d26341276d37a3268f9ce813a728b5";
// The compiled map pack these records were authored and verified against.
// The terrain view static_asserts this equals the compiled pack it binds.
inline constexpr char kBaseCompiledPackSha256[] = "95e187ec51bc0aa5e4998c7da9be025e3ba0c728736df160a20823df6ccf47d5";

enum class EDressingClass : std::uint8_t
{
    CivicFrame = 0,
    ConduitPylon = 1,
};

struct FDressingClass
{
    EDressingClass Class;
    const char* Id;
    const char* MeshReference;
    const char* ReadsAs;
};

inline constexpr FDressingClass kClasses[2] = {
    {EDressingClass::CivicFrame, "civic_frame", "/Game/Art/Generated/World/Environment/SM_World_GlassScarShelf", "pale-ceramic civic frame bastion"},
    {EDressingClass::ConduitPylon, "conduit_pylon", "/Game/Art/Generated/World/Environment/SM_World_GlassScarShard", "interrupted civic conduit pylon"},
};

struct FDressingRecord
{
    EDressingClass Class;
    std::uint8_t X;
    std::uint8_t Y;
    std::uint8_t OrientationOrdinal;
    std::uint8_t ScaleBand;
    std::int32_t CellIndex;
    const char* Id;
};

inline constexpr std::int32_t kRecordCount = 39;
inline constexpr FDressingRecord kRecords[kRecordCount] = {
    {EDressingClass::CivicFrame, 9, 29, 0, 1, 1865, "drs_lr_frame_01"},
    {EDressingClass::CivicFrame, 12, 29, 2, 2, 1868, "drs_lr_frame_02"},
    {EDressingClass::CivicFrame, 14, 29, 0, 1, 1870, "drs_lr_frame_03"},
    {EDressingClass::CivicFrame, 22, 29, 1, 2, 1878, "drs_lr_frame_04"},
    {EDressingClass::CivicFrame, 25, 29, 3, 1, 1881, "drs_lr_frame_05"},
    {EDressingClass::CivicFrame, 27, 29, 1, 2, 1883, "drs_lr_frame_06"},
    {EDressingClass::CivicFrame, 37, 29, 3, 2, 1893, "drs_lr_frame_07"},
    {EDressingClass::CivicFrame, 40, 29, 1, 1, 1896, "drs_lr_frame_08"},
    {EDressingClass::CivicFrame, 42, 29, 3, 2, 1898, "drs_lr_frame_09"},
    {EDressingClass::CivicFrame, 51, 29, 0, 2, 1907, "drs_lr_frame_10"},
    {EDressingClass::CivicFrame, 54, 29, 2, 1, 1910, "drs_lr_frame_11"},
    {EDressingClass::CivicFrame, 21, 37, 1, 2, 2389, "drs_lr_frame_12"},
    {EDressingClass::CivicFrame, 23, 39, 0, 2, 2519, "drs_lr_frame_13"},
    {EDressingClass::CivicFrame, 21, 43, 1, 1, 2773, "drs_lr_frame_14"},
    {EDressingClass::CivicFrame, 43, 37, 2, 2, 2411, "drs_lr_frame_15"},
    {EDressingClass::CivicFrame, 41, 39, 3, 1, 2537, "drs_lr_frame_16"},
    {EDressingClass::CivicFrame, 42, 41, 1, 2, 2666, "drs_lr_frame_17"},
    {EDressingClass::CivicFrame, 40, 43, 0, 1, 2792, "drs_lr_frame_18"},
    {EDressingClass::ConduitPylon, 8, 28, 1, 0, 1800, "drs_lr_pylon_01"},
    {EDressingClass::ConduitPylon, 10, 30, 3, 1, 1930, "drs_lr_pylon_02"},
    {EDressingClass::ConduitPylon, 13, 28, 1, 0, 1805, "drs_lr_pylon_03"},
    {EDressingClass::ConduitPylon, 15, 30, 3, 1, 1935, "drs_lr_pylon_04"},
    {EDressingClass::ConduitPylon, 20, 28, 2, 2, 1812, "drs_lr_pylon_05"},
    {EDressingClass::ConduitPylon, 20, 30, 0, 1, 1940, "drs_lr_pylon_06"},
    {EDressingClass::ConduitPylon, 29, 28, 2, 1, 1821, "drs_lr_pylon_07"},
    {EDressingClass::ConduitPylon, 29, 30, 0, 2, 1949, "drs_lr_pylon_08"},
    {EDressingClass::ConduitPylon, 35, 28, 0, 2, 1827, "drs_lr_pylon_09"},
    {EDressingClass::ConduitPylon, 35, 30, 2, 1, 1955, "drs_lr_pylon_10"},
    {EDressingClass::ConduitPylon, 44, 28, 0, 1, 1836, "drs_lr_pylon_11"},
    {EDressingClass::ConduitPylon, 44, 30, 2, 2, 1964, "drs_lr_pylon_12"},
    {EDressingClass::ConduitPylon, 49, 28, 3, 1, 1841, "drs_lr_pylon_13"},
    {EDressingClass::ConduitPylon, 49, 30, 1, 2, 1969, "drs_lr_pylon_14"},
    {EDressingClass::ConduitPylon, 52, 28, 3, 0, 1844, "drs_lr_pylon_15"},
    {EDressingClass::ConduitPylon, 55, 30, 1, 1, 1975, "drs_lr_pylon_16"},
    {EDressingClass::ConduitPylon, 24, 37, 3, 1, 2392, "drs_lr_pylon_17"},
    {EDressingClass::ConduitPylon, 22, 41, 2, 1, 2646, "drs_lr_pylon_18"},
    {EDressingClass::ConduitPylon, 24, 43, 3, 2, 2776, "drs_lr_pylon_19"},
    {EDressingClass::ConduitPylon, 40, 37, 0, 1, 2408, "drs_lr_pylon_20"},
    {EDressingClass::ConduitPylon, 43, 43, 2, 2, 2795, "drs_lr_pylon_21"},
};

}  // namespace echoes::world::lume_reach_dressing
